kind: Service
apiVersion: v1
metadata:
  name: backend-service
  namespace: backend-app-final
spec:
  type: ClusterIP
  selector:
    app: backend-app
    env: final
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080