spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://ec2-52-31-219-113.eu-west-1.compute.amazonaws.com:5432/d2l9l5ckpt01di}
    username: ${DB_USER:jefniowckghfhw}
    password: ${DB_PASSWORD:cac7a2183afba5ddb8e5c034d4d9ef0c986cee55011a4b3c75293aa19090ed23}
    tomcat:
      test-while-idle: true
      validation-query: 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

